name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@c75e7647e59e2569ff9f4b85107cd181d26e449b
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          allowed-actors: renovate[bot]
